namespace PawnIO;

public enum CpuCodeName : uint
{
	Undefined = uint.MaxValue,
	Colfax = 0u,
	SummitRidge = 8u,
	PinnacleRidge = 9u,
	Threadripper = 4u,
	CastlePeak = 5u,
	RavenRidge = 6u,
	RavenRidge2 = 7u,
	Picasso = 2u,
	Dali = 15u,
	Matisse = 3u,
	Vermeer = 11u,
	Renoir = 1u,
	Lucienne = 22u,
	Cezanne = 13u,
	Vangogh = 12u,
	Milan = 14u,
	Rome = 20u,
	Naples = 18u,
	Rembrandt = 10u,
	Mendocino = 25u,
	Raphael = 16u,
	DragonRange = 28u,
	Chagall = 21u,
	StormPeak = 27u,
	Phoenix = 23u,
	Phoenix2 = 24u,
	HawkPoint = 30u,
	GraniteRidge = 17u,
	FireFlight = 19u,
	Genoa = 26u,
	Bergamo = 37u,
	Turin = 35u,
	TurinD = 36u,
	StrixPoint = 31u,
	StrixHalo = 32u,
	KrackanPoint = 33u,
	KrackanPoint2 = 34u,
	ShimadaPeak = 38u,
	Mero = 29u
}
